### ISSUE TITLE
Must include a notion of "removing" entries from Associated Topology

### ISSUE THREAD

**Issue by dvaccarosenna** [accanto-systems/ignition#80]
Agreed approach is to allow "null/None" entries in the response to indicate an entry in the topology has gone. 

E.g. 
```
# New associated topology entry
myNodeInTheTopology: 
  id: 123
  type: SomeType
```

Later to show this item has been removed:
```
myNodeInTheTopology: null
```
